# encoding: utf-8


group :guard do
end

group :metrics do
end

group :benchmarks do
  gem 'rbench', '~> 0.2.3'
end

platform :jruby do
  group :jruby do
    gem 'jruby-openssl', '~> 0.8.5'
  end
end
